########################################################################################################################
##             ____________________  ________.___                           __                                        ##
##             \______   \______   \/  _____/|   | _______  __ ____   _____/  |_  ___________ ___.__.                 ##
##             |       _/|     ___/   \  ___|   |/    \  \/ // __ \ /    \   __\/  _ \_  __ <   |  |                  ##
##             |    |   \|    |   \    \_\  \   |   |  \   /\  ___/|   |  \  | (  <_> )  | \/\___  |                  ##
##             |____|_  /|____|    \______  /___|___|  /\_/  \___  >___|  /__|  \____/|__|   / ____|                  ##
##             \/                  \/         \/          \/     \/                   \/                              ##
########################################################################################################################
###############
#   By Atzer  #
###############

# For any issues, please open an issue on GitHub (https://github.com/atzer722/RPGInventory) or send a message on Discord (atzer).

menu:
  command: "menu" # The command that will be used to open your menu.
  back_button: "minecraft:cobblestone"
  left_arrow_button: "minecraft:acacia_boat"
  not_equipped_button: "minecraft:gray_dye"
  equipped_button: "minecraft:green_dye"
  right_arrow_button: "minecraft:oak_boat"
  hidden_armor_icon: "minecraft:bedrock"
  # Free Palestine, free Congo, free Ouïghour, free Ukraine, free World.