########################################################################################################################
##             ____________________  ________.___                           __                                        ##
##             \______   \______   \/  _____/|   | _______  __ ____   _____/  |_  ___________ ___.__.                 ##
##             |       _/|     ___/   \  ___|   |/    \  \/ // __ \ /    \   __\/  _ \_  __ <   |  |                  ##
##             |    |   \|    |   \    \_\  \   |   |  \   /\  ___/|   |  \  | (  <_> )  | \/\___  |                  ##
##             |____|_  /|____|    \______  /___|___|  /\_/  \___  >___|  /__|  \____/|__|   / ____|                  ##
##             \/                  \/         \/          \/     \/                   \/                              ##
########################################################################################################################
###############
#   By Atzer  #
###############

# For any issues, please open an issue on GitHub (https://github.com/atzer722/RPGInventory) or send a message on Discord (atzer).

menu:
  command: "dm open main_menu {player}" # The command that will be used to open your menu.
  inventory_texture: "rpginventory:gui_background" # ItemsAdder texture that will be applied to the gui.
  server_execution: true # If the command should be executed by the player (with the player permission) or the server (full permissions) ? (if true, the {player} will be replaced by the player name)
  back_button: "minecraft:cobblestone"
  left_arrow_button: "minecraft:acacia_boat"
  not_equipped_button: "minecraft:gray_dye"
  equipped_button: "minecraft:green_dye"
  right_arrow_button: "minecraft:oak_boat"
  hidden_armor_icon: "minecraft:bedrock"

data:
  # You can use yaml, mysql, sqlite or mariadb.
  # YAML and SQLite is for local data storage. MySQL and MariaDB is for distant data storage
  # As local data storage, we prefer sqlite. As distant data storage, we prefer MariaDB.
  motor: sqlite

  # Distant only. Settings if you chose MySQL or MariaDB as the motor.
  host: "localhost"
  port: 3306
  name: "rpginventory_database"
  username: "root" # For security, you can choose another user.
  password: "For security, choose a strong password."
# Free Palestine, free Congo, free Ouïghour, free Ukraine, free World.